/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background: '#131313',
        surface: '#131313',
        'surface-bright': '#393939',
        'surface-dim': '#131313',
        'surface-variant': '#353534',
        'surface-container': '#201f1f',
        'surface-container-low': '#1c1b1b',
        'surface-container-high': '#2a2a2a',
        'surface-container-highest': '#353534',
        'surface-container-lowest': '#0e0e0e',
        primary: '#adc6ff',
        'primary-container': '#4d8eff',
        'on-primary': '#002e6a',
        'on-primary-container': '#00285d',
        secondary: '#4edea3',
        'secondary-container': '#00a572',
        'on-secondary': '#003824',
        'on-secondary-container': '#00311f',
        tertiary: '#ffb3ad',
        'tertiary-container': '#ff5451',
        'on-tertiary': '#68000a',
        'on-tertiary-container': '#5c0008',
        error: '#ffb4ab',
        'error-container': '#93000a',
        'on-error': '#690005',
        'on-error-container': '#ffdad6',
        'on-surface': '#e5e2e1',
        'on-surface-variant': '#c2c6d6',
        'on-background': '#e5e2e1',
        outline: '#8c909f',
        'outline-variant': '#424754',
        'inverse-surface': '#e5e2e1',
        'inverse-on-surface': '#313030',
        'inverse-primary': '#005ac2',
        'surface-tint': '#adc6ff',
      },
      fontFamily: {
        headline: ['Manrope', 'system-ui', 'sans-serif'],
        body: ['Inter', 'system-ui', 'sans-serif'],
        label: ['Inter', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
    },
  },
  plugins: [],
}
