from abc import ABC, abstractmethod
from dataclasses import dataclass
from datetime import datetime
from typing import Optional

class Event(ABC):
    """
    Base interface for all events in the backtesting system.
    """
    pass

@dataclass
class MarketEvent(Event):
    """
    Event representing new market data availability.
    """
    time: datetime
    symbol: str
    price: float
    volume: int

@dataclass
class SignalEvent(Event):
    """
    Event representing a trading signal generated by the strategy.
    """
    time: datetime
    symbol: str
    signal_type: str  # 'LONG', 'SHORT', 'EXIT'
    strength: float = 1.0
